# Generated by Django 3.2.3 on 2021-05-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acidlord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='photo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
