# Generated by Django 3.2.3 on 2021-05-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acidlord', '0002_harvest_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1000)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acidlord.customer')),
            ],
        ),
    ]
