# Generated by Django 3.2.3 on 2021-05-30 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acidlord', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='harvest',
            name='agronom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='acidlord.agronom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='harvest',
            name='harvest_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='shelf_life',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Agronom2Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agronom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acidlord.agronom')),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acidlord.vacation')),
            ],
        ),
    ]
