# Generated by Django 3.2.3 on 2021-05-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acidlord', '0004_auto_20210530_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='date',
            field=models.DateField(),
        ),
    ]
