# Generated by Django 3.2.3 on 2021-05-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acidlord', '0005_alter_vacation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
